### ISSUE TITLE
Please add PA+LNA version and/or share KiCAD files

### ISSUE THREAD

**Issue by kainhofer** [emc2cube/SMDnRF24_adapter#1]
Thanks a lot for all your nice little nrf24l01 SMD adapters (I have several at home for the raspi gateways). Unfortunately, you only provide the Gerbers for this "normal" nrf24l01 smd to through-hole adapter, while I would like to make an adapter for the PA+LNA version of the SMD nrf24l01 (I have an arduino nano breakout board with a connector for the normal nrf24l01 modules, so I would like to the use PA+LNA SMD version on that normal 2x4 female connector).

If you have no intentions to create such an adapter yourself, would you mind sharing the KiCAD brd files, so I could adjust the board myself (basically, just swap the  smd pins to move GND to the outside)?

Thanks,
Reinhold

**Comment by emc2cube** [comment]
That's a good point, I just released a PA+LNA version.
It is untested so I would appreciate if you could confirm here that it's working properly when you receive your modules, but I don't see why it would not work.

**Comment by kainhofer** [comment]
After a while waiting for the PCBs and then having other things in mind, I finally got around to playing with MySensors again. I can confirm that the PCB for the PA+LNA SMD version of the adapter works.

Thanks a lot for your quick response and your great service!
